service: nestjs-lambda

provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-1
  iam:
    role: arn:aws:iam::950126166338:role/lambda_role
  deploymentBucket:
    name: serverless-nestjs-lambda-deployment-bucket

functions:
  app:
    handler: dist/main.handler
    events:
      - http:
          path: "{proxy+}"
          method: any
